services:
  postegres_keycloak:
    container_name: postegres_keycloak
    image: postgres:15
    ports:
      - '5433:5432'
    environment:
      POSTGRES_DB: postegres
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - banco:/var/lib/postgresql/data
    networks:
      - redes
volumes:
  banco:
networks:
  redes: